version: "3.8"

services:
  web:
    image: webapp:latest
    expose:
      - "80"
    environment:
      - API_URL=http://api.prod.carloshh.local
      - VIRTUAL_HOST=web.prod.carloshh.local
      - VIRTUAL_PORT=80

networks: 
  default: 
    name: infrastructure_network